introduction: Introduction
releaseHistory: Release History
views:
  title: Server Side View Rendering
  thymeleaf: Thymeleaf
  handlebars: Handlebars.java
  velocity: Apache Velocity
  freemarker: Apache Freemarker
  rocker: Rocker
  soy:
    title: Soy/Closure Support
    soyconfiguration: Soy Configuration
    soyusage: Soy Usage
    soyfeaturestemplatesecurity: Soy Features - Template Security
    soyfeaturesremaining: Soy Features - Remaining
    buildingsoy: Building Soy
  pebble: Pebble
  csp: Content Security Policy
  views-security: Security Integration
  graal: GraalVM Support
breaks: Breaking Changes
repository: Repository